### ISSUE TITLE
skeleton

### ISSUE THREAD

**Issue by yegor256** [objectionary/reo#1]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#5](https://github.com/objectionary/reo/issues/5) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#5](https://github.com/objectionary/reo/issues/5) is solved here.
