### ISSUE TITLE
test coverage control is missing

### ISSUE THREAD

**Issue by yegor256** [objectionary/reo#21]
Let's add coverage control to the project. Also, let's publish the results to codecov, like we it in this project, for example: https://github.com/objectionary/eo-files/blob/master/.github/workflows/codecov.yml

**Comment by yegor256** [comment]
@ehsan2754 can you help?

**Comment by Ehsan2754** [comment]
https://github.com/objectionary/reo/pull/36/commits/ab4cb7e3acd83d8387630e59b79a7bc2bb1ac9a1

**Comment by yegor256** [comment]
@Ehsan2754 fixed, thanks!
