### ISSUE TITLE
link

### ISSUE THREAD

**Issue by yegor256** [objectionary/reo#35]
Let's create a new command `link`, which should take a list of `.relf` files and join them all into one:

```
$ reo link target.relf a.relf b.relf c.relf
```

We should rename vertices and edges correctly too.

**Comment by yegor256** [comment]
@Karina5005 try this one too

**Comment by Karina5005** [comment]
@yegor256 Can you give an example of how this command should work? 
I'm not sure I understand the idea of this command, so I don't understand exactly how rename is supposed to work.

**Comment by yegor256** [comment]
@Karina5005 if you "inspect" a RELF file, you will see some vertices there and some edges between them. They all have unique IDs. When we join two or more RELF files, we must be sure that all vertices are still unique. Renaming will be required.

**Comment by Karina5005** [comment]
@yegor256 it can be closed

**Comment by yegor256** [comment]
@Karina5005 thanks!
