### ISSUE TITLE
GitHub Action is failing, while locally the build is clean

### ISSUE THREAD

**Issue by yegor256** [objectionary/reo#37]
For some reason, GitHub Action is failing now with a strange error: https://github.com/objectionary/reo/runs/8243229210?check_suite_focus=true Locally, `cargo clean && cargo test` works on my machine.

**Comment by yegor256** [comment]
@Ehsan2754 please try to help me here

**Comment by Ehsan2754** [comment]
The error is in build action. you mind if I add ur suggesting commands to the build action?

**Comment by yegor256** [comment]
@Ehsan2754 I don't mind, go ahead

**Comment by yegor256** [comment]
@Ehsan2754 this one is fixed already, don't bother
