### ISSUE TITLE
dataize.rs:101-102: This method is very slow. Let's find...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/reo#5]
The puzzle `1-e34f38ca` from #1 has to be resolved: 

https://github.com/objectionary/reo/blob/441f70c142fc02933d336d5af739dc36f185280a/src/universe/dataize.rs#L101-L102

The puzzle was created by @yegor256 on 04-Sep-22. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@Ehsan2754 can you please solve this?

**Comment by yegor256** [comment]
@Ehsan2754 it's not required anymore, I'm closing
