### ISSUE TITLE
Build/Use issue

### ISSUE THREAD

**Issue by Ehsan2754** [objectionary/reo#53]
Currently on master branch last commit, when I run the readme commands line by line, I face this issue.
![image](https://user-images.githubusercontent.com/53513242/193007725-b98847d9-36dc-4e54-a4a2-7fc8bd159e6d.png)

**Comment by yegor256** [comment]
@Ehsan2754 this works for me:

```
$ cargo clean
$ cargo build
$ cargo test
```

Are you sure you are using the latest `master`? What is your OS?

**Comment by yegor256** [comment]
@Ehsan2754 I'm closing. If you have any further problems, please submit a new one
